hundesalon/hundesalon/urls.py
from main import urls as main_url

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include(main_url)),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hundesalon/main/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("bemerkung/<int:pk>", views.bemerkung, name='bemerkung'),
    path('bilder/<int:pk>', views.bilder, name='bilder'),
]

hundesalon/main/models.py
from django.db import models
class Hunderasse(models.Model):
    rasse = models.CharField(max_length=200)

    def __str__(self):
        return self.rasse

    class Meta:
        verbose_name_plural = 'Rassen'
class Kunde(models.Model):
    hundename = models.CharField(max_length=200)
    Rasse = models.ForeignKey(Hunderasse, on_delete=models.SET_NULL, blank=True, null=True)
    birth = models.DateField(blank=True, null=True)
    versichertennummer = models.BooleanField(default=False)
    besonderheiten = models.CharField(max_length=800, blank=True, null=True)

    #kunde
    name = models.CharField(max_length=200)
    vorname = models.CharField(max_length=200)
    tel = models.CharField(max_length=200, blank=True, null=True)
    adresse = models.CharField(max_length=200)
    plz = models.CharField(max_length=20)
    ort = models.CharField(max_length=300)

    def __str__(self):
        return self.hundename

    class Meta:
        verbose_name_plural = 'Kunden'

class Bilder(models.Model):
    bild = models.FileField(upload_to="")
    kunde = models.ForeignKey(Kunde, on_delete=models.CASCADE, blank=True, null=True)
    anzeigebild = models.BooleanField(default=False)

    class Meta:
        verbose_name_plural = 'Bilder'

class Bemerkungen(models.Model):
    text = models.CharField(max_length=8000)
    kunde = models.ForeignKey(Kunde, on_delete=models.CASCADE, blank=True, null=True)
    taetigkeit = models.BooleanField(default=True)

    def __str__(self):
        return self.text

    class Meta:
        verbose_name_plural = 'Bemerkungen'

hundesalon/main/views.py
from django.http import HttpResponse
from django.shortcuts import render
from .models import Kunde, Bemerkungen, Bilder
import socket

def index(request):
    kunde = Kunde.objects.all()

    context = {
        'kunde':kunde,
    }

    return render(request, 'index.html',context)

def bemerkung(request,pk):
    kunde = Kunde.objects.get(pk=pk)

    if request.POST:
        text = request.POST.get('text', None)
        bemerkung = Bemerkungen.objects.create(
            text = text,
            kunde = kunde,
        )
        bemerkung.save()
    bemerkungen = Bemerkungen.objects.filter(kunde=kunde).order_by('-id')

    context = {
        'k':kunde,
        'bemerkungen':bemerkungen,
    }
    return  render(request, 'bemerkung.html', context)


def bilder(request, pk):
    kunde = Kunde.objects.get(pk=pk)
    bilder = Bilder.objects.filter(kunde=kunde)

    if request.method == 'POST' and request.FILES.get('bilder'):
        images = request.FILES.getlist('bilder')
        for image in images:
            Bilder.objects.create(kunde=kunde, bild=image)
        # Redirect or add success message here if needed.

    context = {
        'k': kunde,
        'images': bilder,
    }
    return render(request, 'images.html', context)

hundesalon/templates/bemerkung.html
<div class="card">
  <div class="card-header">
    {{k}}
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item"><input type="text" class="form-control" autofocus name="text" hx-post="{% url 'bemerkung' k.pk %}" hx-target="#content-container"></li>
    {% for b in bemerkungen %}
    <li class="list-group-item">{{b}}</li>
    {% endfor %}
  </ul>
</div>
<script>
  let CSRF_TOKEN = '{{ csrf_token }}';
document.body.addEventListener('htmx:configRequest', (event) => {
    event.detail.headers['X-CSRFToken'] = CSRF_TOKEN;
})

</script>

hundesalon/templates/images.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ k }}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
    <style>
        .card {
            margin-bottom: 20px;
        }
    </style>
</head>
<body>
    <div class="container mt-5">
        <div class="mb-3">
            <label class="form-label">Bilder Hochladen</label>
            <form method="post" action="{% url 'bilder' k.pk %}" enctype="multipart/form-data">
                {% csrf_token %}
                <input class="form-control" name="bilder" type="file" multiple>
                <button type="submit" class="btn btn-primary form-control mt-3">Hochladen</button>
            </form>
        </div>

        <div class="row row-cols-1 row-cols-md-3 g-4">
            {% for image in images %}
            <div class="col">
                <div class="card">
                    <img src="{{ image.bild.url }}" class="card-img-top" alt="...">
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</body>
</html>

hundesalon/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
<script src="https://unpkg.com/htmx.org@1.9.6"></script>
<meta charset="UTF-8">
<title>Hundeschön Selfkant</title>
<style>
    .container {
        display: flex;
        flex-direction: row;
        height: 100vh;
    }

    .card-container {
        width: 50%;
        overflow-y: auto;
        padding: 20px;
    }

    .content-container {
        width: 50%;
        padding: 20px;
    }
</style>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

</head>
<body>
<div class="container">
    <div class="card-container">
        {% for k in kunde %}
        <div class="card mb-6" style="max-width: 540px;">
            <div class="row g-0">
                <div class="col-md-4">
                    <a href="{% url 'bilder' k.pk %}">
                     {% with first_image=k.bilder_set.first %}
                    {% if first_image %}
                        <img src="{{ first_image.bild.url }}" class="img-fluid rounded-start" alt="#bild">
                    {% else %}
                        <img src="{% static 'path/to/default/image.jpg' %}" class="img-fluid rounded-start" alt="#bild">
                    {% endif %}
                {% endwith %}</a>
                </div>
                <div class="col-md-8">
                    <div class="card-body" hx-get="{% url 'bemerkung' k.pk %}" hx-target="#content-container">
                        <h5 class="card-title">{{k.hundename}}</h5>
                        <p class="card-text">{{k.rasse}}<br>
                            {{k.birth}}<br>
                            Versichertennummer: {{k.versichertennummer|yesno:"ja,nein,vielleicht" }}
                            <hr>
                            <small class="text-muted">Kunde</small><br>
                            {{k.vorname}} {{k.name}} <br>
                            {{k.tel}}<br>
                            {{k.adresse}}<br>
                            {{k.plz}} {{k.ort}}
                        </p>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    <div class="content-container" id="content-container">
    </div>
</div>



</body>
</html>

hundesalon/templates/kundenaufnahmebogen.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>